[2024-07-20 20:25:10,582 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.29.123:5000
[2024-07-20 20:25:10,584 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-07-20 20:27:36,946 ] 97 werkzeug - INFO - 127.0.0.1 - - [20/Jul/2024 20:27:36] "GET /predictdata HTTP/1.1" 200 -
[2024-07-20 20:27:42,412 ] 97 werkzeug - INFO - 127.0.0.1 - - [20/Jul/2024 20:27:42] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-07-20 20:29:41,446 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "D:\project\ml project\src\pipeline\predict_pipeline.py", line 13, in predict
    try:
        
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\project\ml project\myeve\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\ml project\myeve\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\ml project\myeve\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\ml project\myeve\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\ml project\app.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\ml project\src\pipeline\predict_pipeline.py", line 24, in predict
    except Exception as e:
        ^^^^^^^^^^^^^^^^^^
src.exception.CustomException: Error occured in python script name [D:\project\ml project\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[2024-07-20 20:29:41,515 ] 97 werkzeug - INFO - 127.0.0.1 - - [20/Jul/2024 20:29:41] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
